### ISSUE TITLE
More comprehensive timezone information?

### ISSUE THREAD

**Issue by Kkevsterrr** [jeroenj/geo_ip#11]
Would it be possible to retrieve more timezone information other than the UTC offset? Because of daylight savings time issues, having the UTC offset is not enough to find an exact timezone.  Thanks otherwise for the great work!

**Comment by jeroenj** [comment]
The UTF offset is the only data that is sent back from the [API](http://ipinfodb.com/ip_location_api_json.php). You might open a support ticket with them to add DST data to the api. If they do I can add it to the gem.
