### ISSUE TITLE
Remove rest-client dependency

### ISSUE THREAD

**Issue by jeroenj** [jeroenj/geo_ip#16]
I'd like this gem to be dependency free. I've already [removed](https://github.com/jeroenj/geo_ip/commit/c3a0f0eb10b2a3848b9bd0847a871747570701a0) the `json` dependency.

`Net::HTTP` should be used instead.

**Comment by elfenars** [comment]
#17

**Comment by elfenars** [comment]
#20

**Comment by jeroenj** [comment]
Closed by #20.
